repos:
  - repo: 'https://github.com/charliermarsh/ruff-pre-commit'
    rev: v0.0.285
    hooks:
      - id: ruff
        args:
          - '--line-length=120'
          - '--fix'
          - '--exit-non-zero-on-fix'
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
  - repo: 'https://github.com/pycqa/isort'
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args:
          - '--profile'
          - black
          - '--filter-files'
  - repo: 'https://github.com/psf/black'
    rev: 23.7.0
    hooks:
      - id: black
        args:
          - '--line-length=120'
