repos:
  - repo: 'https://github.com/charliermarsh/ruff-pre-commit'
    rev: v0.14.0
    hooks:
      - id: ruff-check
        args:
          - '--fix'
          - '--exit-non-zero-on-fix'
      - id: ruff-format
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args:
          - '--maxkb=2048'  # allow screenshots
