site_name: actualpy Documentation
strict: true
site_description: A Python re-implementation of the NodeJS API for Actual Budget
repo_name: bvanelli/actualpy
repo_url: https://github.com/bvanelli/actualpy
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
- search
- mkdocstrings:
    handlers:
          python:
            import:
            - https://docs.python.org/3/objects.inv
            options:
              docstring_style: sphinx
              docstring_options:
                ignore_init_summary: true
              docstring_section_style: list
              filters: ["!^_"]
              heading_level: 1
              inherited_members: true
              merge_init_into_class: true
              parameter_headings: true
              separate_signature: true
              members_order: source
              show_root_heading: true
              show_root_full_path: false
              show_signature_annotations: true
              show_symbol_type_heading: true
              show_symbol_type_toc: true
              signature_crossrefs: true
              summary: true
              extensions:
                - griffe_fieldz: { include_inherited: true }
