name: Try building the documentation to prevent cross-reference issues

on:
  pull_request:

jobs:
  try-build-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Install uv and set the python version
      uses: astral-sh/setup-uv@v6
      with:
        python-version: 3.13
    - name: Install project dependencies
      run: uv sync --extra docs
    - name: Try building the documentation
      run: uv run mkdocs build
