name: Try building the documentation to prevent cross-reference issues

on:
  pull_request:

jobs:
  try-build-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.13"
    - name: Install project dependencies
      run: python3 -m pip install --user -r docs/requirements.txt
    - name: Try building the documentation
      run: mkdocs build
